version: "3.9"

services:
  eureka-server:
    container_name: eureka-server
    build:
      context: eureka-server
      dockerfile: Dockerfile
    image: eureka-server:latest
    ports:
      - "8761:8761"

  minio:
    container_name: minio
    image: bitnami/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=12345678
      - MINIO_SERVER_ACCESS_KEY=BZBoSB7ab85niUgOtQdF
      - MINIO_SERVER_SECRET_KEY=RKayUx8MKRccsHfHfIYSjo9duFUUX0loZNI4GT5J