version: "3.9"

services:
  db-GeneratorUrl:
    image: postgres:alpine3.19
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: GeneratorUrl

  db-paste-service:
    image: postgres:alpine3.19
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: paste-service

  minio:
    container_name: minio
    image: bitnami/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=12345678

  eureka-server:
    container_name: eureka-server
    build:
      context: eureka-server
      dockerfile: Dockerfile
    image: eureka-server:latest
    ports:
      - "8761:8761"

  GeneratorUrl:
    container_name: GeneratorUrl
    build:
      context: GeneratorUrl
      dockerfile: Dockerfile
    image: generator-url:latest
    ports:
      - "8081:8081"
    depends_on:
      - db-GeneratorUrl
      - eureka-server

  paste-service:
    container_name: paste-service
    build:
      context: paste-service
      dockerfile: Dockerfile
    image: paste-service:latest
    ports:
      - "8080:8080"
    depends_on:
      - db-paste-service
      - minio
      - GeneratorUrl
      - eureka-server